In [2]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [4]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 5, 6]] ) 

In [8]:
np.shape(arr)

(2, 3)

In [10]:
 arr = np.arange(10)

In [11]:


arr.T.dot(arr)

285

In [12]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
np.power(arr, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])